name: Deploy Hexo Blog via SFTP

on:
  push:
    branches:
      - main  # 你部署的分支名稱，依實際調整

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 下載程式碼
        uses: actions/checkout@v3

      - name: 安裝 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 安裝 Hexo 並產生靜態檔
        run: |
          npm install hexo-cli -g
          npm install
          hexo g

      - name: 上傳到 SFTP 伺服器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: itamiokanjiro.ddns.net
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "public/*"
          target: "/var/www/html2"

